### ISSUE TITLE
proxyClass is reall not require?

### ISSUE THREAD

**Issue by xingxuan** [vert-x3/vertx-service-proxy#39]
: Unhandled exception
java.lang.IllegalStateException: Cannot find proxyClass: com.miaozhen.vertx.cluster.consumer.HelloServiceVertxProxyHandler
	at io.vertx.serviceproxy.ProxyHelper.loadClass(ProxyHelper.java:104)
	at io.vertx.serviceproxy.ProxyHelper.registerService(ProxyHelper.java:78)
	at io.vertx.serviceproxy.ProxyHelper.registerService(ProxyHelper.java:71)
	at io.vertx.serviceproxy.ProxyHelper.registerService(ProxyHelper.java:65)
	at com.miaozhen.vertx.cluster.consumer.ServiceVerticle.lambda$0(ServiceVerticle.java:58)
	at io.vertx.core.impl.VertxImpl.lambda$createAndStartEventBus$267(VertxImpl.java:177)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$null$125(ClusteredEventBus.java:94)
	at io.vertx.core.net.impl.NetServerImpl.lambda$null$32(NetServerImpl.java:252)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.miaozhen.vertx.cluster.consumer.HelloServiceVertxProxyHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.serviceproxy.ProxyHelper.loadClass(ProxyHelper.java:102)
	... 12 more

**Comment by xingxuan** [comment]
Your case is too old，and can not run normally
